### ISSUE TITLE
checkURL fails on certain bodies

### ISSUE THREAD

**Issue by HSchmale16** [knights-analytics/hugot#25]
Hi,

I'm having a great deal of difficultly downloading this model: https://huggingface.co/nickmuchi/sec-bert-finetuned-finance-classification/tree/main

I'm getting an error about it failing to deserialize the hfFile. However I've compared the responses of the hugging face api and I cannot see any difference in the structures.

It's failing around line 120 of downloader.go.

Any help you can provide would be greatly appreciated.

**Comment by sedletsky-f5** [comment]
you can download it yourself and use locally (without `downloader.go`)

**Comment by RJKeevil** [comment]
Thanks for the report, i've fixed the issue and started a PR. The workaround above of manually downloading will work in the meantime.

**Comment by HSchmale16** [comment]
So what I ended up doing was adding several git clones to my deployment script. Maybe it makes sense to add a dependency on git instead
