### ISSUE TITLE
`tokenizers` fork: Include upstream changes for platform dependent libs in CGO

### ISSUE THREAD

**Issue by gregfurman** [knights-analytics/hugot#33]
Hey 👋 

Thanks for this library. I'm currently using it to build some inference tooling plugins for a stream processor.

Can the `knights-analytics/tokenizer` fork be updated to include [PR/18 Update to allow for platform dependent libs in CGO](https://github.com/daulet/tokenizers/pull/18)?

Think this will make compilation a bit easier, especially for people like me who are on a Mac where `/usr/lib` is a protected directory as including that `tokenizers_srcdir_relative` is not really ideal when building.

https://github.com/daulet/tokenizers/blob/d9aff87d16f3db537ee005fb45ebca26049e7916/tokenizer.go#L6

**Comment by RJKeevil** [comment]
FYI PR is here https://github.com/daulet/tokenizers/pull/21

**Comment by RJKeevil** [comment]
This change is now part of the v0.1.4 release
