### ISSUE TITLE
[Feature Request] Include Docker images with each release

### ISSUE THREAD

**Issue by gregfurman** [knights-analytics/hugot#38]
It would be extremely helpful to include Docker images with each release that include the `tokenizer` and compiled C libraries required to run `hugot`.

I'm busy writing integration tests that need to be run platform independently (due to the dependencies) and it's currently not viable to build my own `hugot` image. This will also be very useful as a base-image to build upon.

Thanks!

**Comment by riccardopinosio** [comment]
Hi @gregfurman, on this one, I could look at generating the docker image with hugot and putting it on dockerhub? I would probably do it without multi-platform build for now (i.e. image would be build for linux/amd64), would that work?

**Comment by gregfurman** [comment]
Hey @riccardopinosio.

Dockerhub works for me!, otherwise GitHub's container registry is another option to consider. 

Regarding platform, `linux/amd64` is perfect 😄

**Comment by riccardopinosio** [comment]
@gregfurman i added a step to upload a docker image with the hugot release. The image includes the hugot dependencies (onnxruntime and tokenizer) and can be found in the github docker repository on the main page.
