### ISSUE TITLE
[Bug] Text Classification pipeline's panic when model has `token Type IDs`

### ISSUE THREAD

**Issue by gregfurman** [knights-analytics/hugot#41]
If a Text Classification pipeline has [token type IDs](https://huggingface.co/docs/transformers/glossary#token-type-ids), the current `BasePipeline.Preprocess` will fail since there is no `WithReturnTypeIDs` option provided to the `textClassification` pipeline's `TokenizerOptions`:

https://github.com/knights-analytics/hugot/blob/fd59728f69cd76fb3e011a89929de441edd7bc52/pipelines/textClassification.go#L97-L99

This means that `input.TypeIds` is an empty slice and will cause a `panic: runtime error: index out of range [0] with length 0`:
https://github.com/knights-analytics/hugot/blob/fd59728f69cd76fb3e011a89929de441edd7bc52/pipelines/pipeline.go#L308-L310

The tokenizer options for text classification pipelines should include a `tokenizers.WithReturnTypeIDs()`, similar to the other pipeline types:

```go
pipeline.TokenizerOptions = []tokenizers.EncodeOption{
	tokenizers.WithReturnAttentionMask(),
	tokenizers.WithReturnTypeIDs(),
}
```

---

Tested on [ProsusAI/finbert](https://huggingface.co/ProsusAI/finbert) converted to ONNX using [`optimum CLI v1.21.2`](https://github.com/huggingface/optimum)

**Comment by RJKeevil** [comment]
Making a more general change to configure the tokenizer via the onnx model metadata inputs, should be more flexible to different models and means we dont return things we dont use. Nice request thanks!
