### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by riccardopinosio** [knights-analytics/hugot#9]
Since we rely on onnxruntime it should be fairly straightforward to support GPU for the pipelines.

**Comment by sedletsky-f5** [comment]
is there a plan to support GPU?

**Comment by riccardopinosio** [comment]
@sedletsky-f5 hi, there sure is, as onnxruntime should make that relatively painless. I haven't gotten around to it yet, wanted to add support for a couple more pipelines first, but could look at it earlier if you think it's important for you application

**Comment by RJKeevil** [comment]
Today i started a new branch (gpu-support) which exposes all the options for the available providers.  If you want to try a pre alpha version i think the remaining work is to select an appropriate gpu-enabled onnxruntime library from https://github.com/microsoft/onnxruntime/releases , then test this in an environment with the right OS dependencies/libraries.  Let us know if you try this early.

**Comment by RJKeevil** [comment]
Cuda is now fully working for me on the GPU branch, so now would be a good time to try it if you like.  We'll release this imminently.

**Comment by sedletsky-f5** [comment]
sorry, missed previous messages - yes, it is important for my project and I will test `gpu-support` branch shortly. thanks a lot!

**Comment by riccardopinosio** [comment]
Hi @sedletsky-f5, this is now implemented in main (new release 0.1.0).
